#!/usr/bin/env bash
#File Transfer
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
