#!/usr/bin/env bash
#test
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default-backup
redirect="\n\tserver_name anthonyhuggins.tech;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
error="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "36i\ $error" /etc/nginx/sites-available/default
sudo service nginx start
