#!/usr/bin/env bash
# this is a comment
_term()
{
	echo "I hate the kill command"
	rm /var/run/holbertonscript.pid
	exit 1
}
_int()
{
	echo "Y U no love me?!"
}
_quit()
{
	rm /var/run/holbertonscript.pid
	exit 1
}

trap _term SIGTERM
trap _int SIGINT
trap _quit SIGQUIT
echo $$ > /var/run/holbertonscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
