#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 9 ]
	then
		echo "Holberton School"
		echo "Hi"
	else
		echo "Holberton School"
	fi
	i=$(( i + 1 ))
done
